/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * FlowNews API
 * OpenAPI spec version: v1
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  TopicHistoryRecordRequest
} from '.././models';

import { axiosInstance } from '.././axiosInstance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const recordTopicHistory = (
    topicId: number,
    topicHistoryRecordRequest: TopicHistoryRecordRequest,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<null>(
      {url: `/topics/${topicId}/read`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: topicHistoryRecordRequest, signal
    },
      options);
    }
  


export const getRecordTopicHistoryMutationOptions = <TError = string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof recordTopicHistory>>, TError,{topicId: number;data: TopicHistoryRecordRequest}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof recordTopicHistory>>, TError,{topicId: number;data: TopicHistoryRecordRequest}, TContext> => {

const mutationKey = ['recordTopicHistory'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof recordTopicHistory>>, {topicId: number;data: TopicHistoryRecordRequest}> = (props) => {
          const {topicId,data} = props ?? {};

          return  recordTopicHistory(topicId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RecordTopicHistoryMutationResult = NonNullable<Awaited<ReturnType<typeof recordTopicHistory>>>
    export type RecordTopicHistoryMutationBody = TopicHistoryRecordRequest
    export type RecordTopicHistoryMutationError = string

    export const useRecordTopicHistory = <TError = string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof recordTopicHistory>>, TError,{topicId: number;data: TopicHistoryRecordRequest}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof recordTopicHistory>>,
        TError,
        {topicId: number;data: TopicHistoryRecordRequest},
        TContext
      > => {

      const mutationOptions = getRecordTopicHistoryMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    