/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * FlowNews API
 * OpenAPI spec version: v1
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  EventFeedResponse
} from '.././models';

import { axiosInstance } from '.././axiosInstance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 인증된 사용자의 개인화된 이벤트 피드의 이벤트 ID 목록을 반환합니다. 각 이벤트의 상세 정보는 /events/{id} 엔드포인트로 별도 요청해야 합니다.
 * @summary 사용자별 이벤트 피드 조회
 */
export const getUserEventFeed = (
    
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<EventFeedResponse>(
      {url: `/events/feed`, method: 'GET', signal
    },
      options);
    }
  

export const getGetUserEventFeedQueryKey = () => {
    return [`/events/feed`] as const;
    }

    
export const getGetUserEventFeedQueryOptions = <TData = Awaited<ReturnType<typeof getUserEventFeed>>, TError = string>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserEventFeed>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserEventFeedQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserEventFeed>>> = ({ signal }) => getUserEventFeed(requestOptions, signal);

      

      

   return  { queryKey, queryFn,   staleTime: 300000, refetchOnWindowFocus: false,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserEventFeed>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserEventFeedQueryResult = NonNullable<Awaited<ReturnType<typeof getUserEventFeed>>>
export type GetUserEventFeedQueryError = string


export function useGetUserEventFeed<TData = Awaited<ReturnType<typeof getUserEventFeed>>, TError = string>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserEventFeed>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserEventFeed>>,
          TError,
          Awaited<ReturnType<typeof getUserEventFeed>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserEventFeed<TData = Awaited<ReturnType<typeof getUserEventFeed>>, TError = string>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserEventFeed>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserEventFeed>>,
          TError,
          Awaited<ReturnType<typeof getUserEventFeed>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserEventFeed<TData = Awaited<ReturnType<typeof getUserEventFeed>>, TError = string>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserEventFeed>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 사용자별 이벤트 피드 조회
 */

export function useGetUserEventFeed<TData = Awaited<ReturnType<typeof getUserEventFeed>>, TError = string>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserEventFeed>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserEventFeedQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



