/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * FlowNews API
 * OpenAPI spec version: v1
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  TopicDetailsResponse
} from '.././models';

import { axiosInstance } from '.././axiosInstance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getTopicDetails = (
    id: number,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<TopicDetailsResponse>(
      {url: `/topics/${id}`, method: 'GET', signal
    },
      options);
    }
  

export const getGetTopicDetailsQueryKey = (id?: number,) => {
    return [`/topics/${id}`] as const;
    }

    
export const getGetTopicDetailsQueryOptions = <TData = Awaited<ReturnType<typeof getTopicDetails>>, TError = string>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTopicDetails>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTopicDetailsQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTopicDetails>>> = ({ signal }) => getTopicDetails(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  staleTime: 300000, refetchOnWindowFocus: false,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTopicDetails>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTopicDetailsQueryResult = NonNullable<Awaited<ReturnType<typeof getTopicDetails>>>
export type GetTopicDetailsQueryError = string


export function useGetTopicDetails<TData = Awaited<ReturnType<typeof getTopicDetails>>, TError = string>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTopicDetails>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTopicDetails>>,
          TError,
          Awaited<ReturnType<typeof getTopicDetails>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTopicDetails<TData = Awaited<ReturnType<typeof getTopicDetails>>, TError = string>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTopicDetails>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTopicDetails>>,
          TError,
          Awaited<ReturnType<typeof getTopicDetails>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTopicDetails<TData = Awaited<ReturnType<typeof getTopicDetails>>, TError = string>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTopicDetails>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetTopicDetails<TData = Awaited<ReturnType<typeof getTopicDetails>>, TError = string>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTopicDetails>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTopicDetailsQueryOptions(id,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



