/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * FlowNews API
 * OpenAPI spec version: v1
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  PushMessageSendRequest,
  SendPushMessageByTopic200
} from '.././models';

import { axiosInstance } from '.././axiosInstance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const sendPushMessageByTopic = (
    pushMessageSendRequest: PushMessageSendRequest,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<SendPushMessageByTopic200>(
      {url: `/notifications/push`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pushMessageSendRequest, signal
    },
      options);
    }
  


export const getSendPushMessageByTopicMutationOptions = <TError = string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendPushMessageByTopic>>, TError,{data: PushMessageSendRequest}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof sendPushMessageByTopic>>, TError,{data: PushMessageSendRequest}, TContext> => {

const mutationKey = ['sendPushMessageByTopic'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof sendPushMessageByTopic>>, {data: PushMessageSendRequest}> = (props) => {
          const {data} = props ?? {};

          return  sendPushMessageByTopic(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SendPushMessageByTopicMutationResult = NonNullable<Awaited<ReturnType<typeof sendPushMessageByTopic>>>
    export type SendPushMessageByTopicMutationBody = PushMessageSendRequest
    export type SendPushMessageByTopicMutationError = string

    export const useSendPushMessageByTopic = <TError = string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendPushMessageByTopic>>, TError,{data: PushMessageSendRequest}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof sendPushMessageByTopic>>,
        TError,
        {data: PushMessageSendRequest},
        TContext
      > => {

      const mutationOptions = getSendPushMessageByTopicMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    