/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as TopicsTopicIdImport } from './routes/topics/$topicId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TopicsTopicIdRoute = TopicsTopicIdImport.update({
  id: '/topics/$topicId',
  path: '/topics/$topicId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/topics/$topicId': {
      id: '/topics/$topicId'
      path: '/topics/$topicId'
      fullPath: '/topics/$topicId'
      preLoaderRoute: typeof TopicsTopicIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/topics/$topicId': typeof TopicsTopicIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/topics/$topicId': typeof TopicsTopicIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/topics/$topicId': typeof TopicsTopicIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/topics/$topicId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/topics/$topicId'
  id: '__root__' | '/' | '/topics/$topicId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TopicsTopicIdRoute: typeof TopicsTopicIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TopicsTopicIdRoute: TopicsTopicIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/topics/$topicId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/topics/$topicId": {
      "filePath": "topics/$topicId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
