/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * FlowNews API
 * OpenAPI spec version: v1
 */

export interface Article {
  id?: number;
  event: unknown;
  title: string;
  source: string;
  url: string;
}
