/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * FlowNews API
 * OpenAPI spec version: v1
 */
import type { User } from './user';
import type { Event } from './event';

export interface Bookmark {
  id?: number;
  user: User;
  event: Event;
  isDeleted: boolean;
  createdAt: string;
  modifiedAt: string;
  deleted?: boolean;
}
