/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * FlowNews API
 * OpenAPI spec version: v1
 */

/**
 * 이벤트 항목 정보
 */
export interface EventItemQueryResponse {
  /** 이벤트 고유 ID */
  id: number;
  /** 이벤트 제목 */
  title: string;
  /** 이벤트 내용 */
  content: string;
  /** 이벤트 이미지 URL */
  imageUrl: string;
  /** 이벤트 발생 시간 */
  eventTime: string;
  /** 좋아요 수 */
  likeCount: number;
  /** 사용자의 좋아요 여부 */
  isLiked: boolean;
}
