/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * FlowNews API
 * OpenAPI spec version: v1
 */
import type { Article } from './article';
import type { TopicEvent } from './topicEvent';
import type { Bookmark } from './bookmark';

export interface Event {
  id?: number;
  title: string;
  description: string;
  imageUrl: string;
  eventTime: string;
  viewCount: number;
  embedding?: number[];
  articles: Article[];
  topicEvents: TopicEvent[];
  bookmarks: Bookmark[];
  totalReactionsCount: number;
  createdAt: string;
  modifiedAt: string;
}
