/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * FlowNews API
 * OpenAPI spec version: v1
 */

/**
 * 이벤트 피드 응답
 */
export interface EventFeedResponse {
  /** 이벤트 ID 목록 */
  eventIds: number[];
}
