/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * FlowNews API
 * OpenAPI spec version: v1
 */
import type { Article } from './article';
import type { TopicEvent } from './topicEvent';
import type { Reaction } from './reaction';
import type { Bookmark } from './bookmark';

export interface Event {
  id?: number;
  title: string;
  description: string;
  imageUrl: string;
  eventTime: string;
  viewCount: number;
  articles: Article[];
  topicEvents: TopicEvent[];
  reactions: Reaction[];
  bookmarks: Bookmark[];
  createdAt: string;
  modifiedAt: string;
}
