/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * FlowNews API
 * OpenAPI spec version: v1
 */
import type { TopicSectionListQueryResponse } from './topicSectionListQueryResponse';
import type { TopicSummaryResponse } from './topicSummaryResponse';

export type GetAllTopics200 = TopicSectionListQueryResponse | TopicSummaryResponse[];
