/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * FlowNews API
 * OpenAPI spec version: v1
 */

export type GetInteractionCountForEventInteractionType = typeof GetInteractionCountForEventInteractionType[keyof typeof GetInteractionCountForEventInteractionType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetInteractionCountForEventInteractionType = {
  VIEWED: 'VIEWED',
  ARTICLE_CLICKED: 'ARTICLE_CLICKED',
  TOPIC_VIEWED: 'TOPIC_VIEWED',
  TOPIC_FOLLOWED: 'TOPIC_FOLLOWED',
  TOPIC_UNFOLLOWED: 'TOPIC_UNFOLLOWED',
} as const;
