/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * FlowNews API
 * OpenAPI spec version: v1
 */

export interface InteractionRecordResponse {
  id: number;
  success: boolean;
  message: string;
}
