/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * FlowNews API
 * OpenAPI spec version: v1
 */
import type { InteractionRecordRequestInteractionType } from './interactionRecordRequestInteractionType';

export interface InteractionRecordRequest {
  eventId: number;
  interactionType: InteractionRecordRequestInteractionType;
  additionalData?: string;
}
