/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * FlowNews API
 * OpenAPI spec version: v1
 */

export interface ReactionSummaryResponse {
  reactionTypeName: string;
  count: number;
}
