/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * FlowNews API
 * OpenAPI spec version: v1
 */

/**
 * 반응 토글 응답
 */
export interface ReactionToggleResponse {
  /** 반응 활성화 상태 */
  isActive: boolean;
  /** 응답 메시지 */
  message: string;
  /** 해당 반응의 총 개수 */
  count: number;
}
