/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * FlowNews API
 * OpenAPI spec version: v1
 */
import type { User } from './user';
import type { ReactionType } from './reactionType';

export interface Reaction {
  id?: number;
  user: User;
  event: unknown;
  reactionType: ReactionType;
  isDeleted?: string;
  createdAt: string;
  modifiedAt: string;
  deleted?: string;
}
