/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * FlowNews API
 * OpenAPI spec version: v1
 */
import type { Topic } from './topic';

export interface TopicEvent {
  id?: number;
  topic: Topic;
  event: unknown;
  createdAt: string;
  modifiedAt: string;
}
