/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * FlowNews API
 * OpenAPI spec version: v1
 */
import type { EventSummaryResponse } from './eventSummaryResponse';

/**
 * 토픽 상세 조회 응답
 */
export interface TopicQueryResponse {
  /** 토픽 고유 ID */
  id: number;
  /** 토픽 제목 */
  title: string;
  /** 토픽 설명 */
  description: string;
  /** 토픽에 포함된 이벤트 목록 */
  events: EventSummaryResponse[];
  /** 사용자의 토픽 팔로우 여부 */
  isFollowing: boolean;
}
