/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * FlowNews API
 * OpenAPI spec version: v1
 */
import type { TopicEvent } from './topicEvent';
import type { Event } from './event';

export interface Topic {
  id?: number;
  title: string;
  description: string;
  topicEvents: TopicEvent[];
  createdAt: string;
  modifiedAt: string;
  lastEvent?: Event;
  events: Event[];
}
