/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * FlowNews API
 * OpenAPI spec version: v1
 */

/**
 * 토픽 구독 토글 응답
 */
export interface TopicSubscriptionToggleResponse {
  /** 구독 상태 */
  isSubscribed: boolean;
  /** 응답 메시지 */
  message: string;
}
