/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * FlowNews API
 * OpenAPI spec version: v1
 */
import type { TopicEventId } from './topicEventId';
import type { Topic } from './topic';
import type { Event } from './event';

export interface TopicEvent {
  id: TopicEventId;
  topic: Topic;
  event: Event;
  createdAt: string;
}
