/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * FlowNews API
 * OpenAPI spec version: v1
 */
import type { EventSummaryResponse } from './eventSummaryResponse';
import type { TopicSummaryResponse } from './topicSummaryResponse';

export interface TopicDetailsResponse {
  id: number;
  title: string;
  description: string;
  imageUrl: string;
  isFollowing: boolean;
  lastReadEvent?: number;
  events: EventSummaryResponse[];
  recommendTopics: TopicSummaryResponse[];
}
