/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * FlowNews API
 * OpenAPI spec version: v1
 */
import type { TopicSectionListItem } from './topicSectionListItem';

export interface TopicSectionListQueryResponse {
  sections: TopicSectionListItem[];
}
