/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * FlowNews API
 * OpenAPI spec version: v1
 */

export interface TopicHistoryRecordRequest {
  topicId: number;
  eventId?: number;
  ipAddress: string;
  elapsedTime: number;
  direction: string;
}
