/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * FlowNews API
 * OpenAPI spec version: v1
 */

export interface UserQueryResponse {
  id: number;
  name: string;
  email: string;
  profileUrl?: string;
  role: string;
  isProfileComplete: boolean;
}
