/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * FlowNews API
 * OpenAPI spec version: v1
 */
import type { UserRole } from './userRole';
import type { UserGender } from './userGender';
import type { Bookmark } from './bookmark';

export interface User {
  id?: number;
  oauthId: string;
  provider: string;
  name: string;
  email: string;
  profileUrl?: string;
  role: UserRole;
  deviceToken?: string;
  birthDate?: string;
  gender?: UserGender;
  createdAt: string;
  modifiedAt: string;
  bookmarks: Bookmark[];
}
