/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * FlowNews API
 * OpenAPI spec version: v1
 */
import type { User } from './user';
import type { Event } from './event';
import type { UserEventInteractionInteractionType } from './userEventInteractionInteractionType';

export interface UserEventInteraction {
  id?: number;
  user: User;
  event: Event;
  interactionType: UserEventInteractionInteractionType;
  additionalData?: string;
  createdAt: string;
  modifiedAt: string;
}
