/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * FlowNews API
 * OpenAPI spec version: v1
 */
import type { UserProfileUpdateResponseGender } from './userProfileUpdateResponseGender';

export interface UserProfileUpdateResponse {
  id: number;
  email: string;
  name: string;
  birthDate?: string;
  gender?: UserProfileUpdateResponseGender;
  isProfileComplete: boolean;
}
