/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * FlowNews API
 * OpenAPI spec version: v1
 */
import type { UserProfileUpdateRequestGender } from './userProfileUpdateRequestGender';

export interface UserProfileUpdateRequest {
  birthDate: string;
  gender: UserProfileUpdateRequestGender;
}
