/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * FlowNews API
 * OpenAPI spec version: v1
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  SubscribeTopic200,
  UserDeviceTokenUpdateRequest
} from '.././models';

import { axiosInstance } from '.././axiosInstance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const subscribeTopic = (
    topicId: number,
    userDeviceTokenUpdateRequest: UserDeviceTokenUpdateRequest,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<SubscribeTopic200>(
      {url: `/topics/${topicId}/subscribe`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: userDeviceTokenUpdateRequest, signal
    },
      options);
    }
  


export const getSubscribeTopicMutationOptions = <TError = string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof subscribeTopic>>, TError,{topicId: number;data: UserDeviceTokenUpdateRequest}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof subscribeTopic>>, TError,{topicId: number;data: UserDeviceTokenUpdateRequest}, TContext> => {

const mutationKey = ['subscribeTopic'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof subscribeTopic>>, {topicId: number;data: UserDeviceTokenUpdateRequest}> = (props) => {
          const {topicId,data} = props ?? {};

          return  subscribeTopic(topicId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SubscribeTopicMutationResult = NonNullable<Awaited<ReturnType<typeof subscribeTopic>>>
    export type SubscribeTopicMutationBody = UserDeviceTokenUpdateRequest
    export type SubscribeTopicMutationError = string

    export const useSubscribeTopic = <TError = string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof subscribeTopic>>, TError,{topicId: number;data: UserDeviceTokenUpdateRequest}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof subscribeTopic>>,
        TError,
        {topicId: number;data: UserDeviceTokenUpdateRequest},
        TContext
      > => {

      const mutationOptions = getSubscribeTopicMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    